### ISSUE TITLE
Doesn't read the rounds for me

### ISSUE THREAD

**Issue by 123JLaney123** [ThreesFG/FallGuysStats#1]
I did everything as instructed, nothing. Even tried clearing the database stuff entirely, nothing. Tried manually setting the log path, nothing. What could be the cause? It works perfectly fine for my friend.

**Comment by ThreesFG** [comment]
@123JLaney123 Was the info showing up on the overlay during the game?

**Comment by ThreesFG** [comment]
@123JLaney123 Would be interested in knowing if the latest version I just posted fixes your issue.

**Comment by 123JLaney123** [comment]
> @123JLaney123 Was the info showing up on the overlay during the game?

No, it was reading the last round I played before the ShootMe tracker broke.

**Comment by 123JLaney123** [comment]
> @123JLaney123 Would be interested in knowing if the latest version I just posted fixes your issue.

I'll try it now, thanks

**Comment by 123JLaney123** [comment]
No difference 🤷

**Comment by ThreesFG** [comment]
@123JLaney123 Have you tried manually setting your Log File path in the settings?

**Comment by 123JLaney123** [comment]
Yeah I tried and it didn't work.
Edit: Just saw the ShootMe tracker update and that works for me, weird.

**Comment by 123JLaney123** [comment]
Hi, just realised I can still comment here even with the issue closed.
I wanted to ask, how does the fix you made time the rounds exactly? I'm trying to compare three different trackers and their accuracies. I help run the Fall Guys World Record Discord so this is kinda important.

One of the other two trackers (FallGuysRecord) seems a bit inconsistent, and I'm not sure how it works. The other is FallGuysRecord modded by mzj21 and that one seems really consistent, and the creator told me how it measures the round times. So I was curious how your fix works?

**Comment by ThreesFG** [comment]
@123JLaney123 The code that does this can be seen here: https://github.com/ShootMe/FallGuysStats/blob/master/Entities/LogFileRewriter.cs

It basically reads the Fall Guys log in realtime, injects the current time, and writes the row to another file. The stat tracker then does it's normal parsing against this new file. Times are pretty close, but not exact.

**Comment by 123JLaney123** [comment]
I appreciate the response but I know nothing about coding so understanding that is difficult for me.
![image](https://user-images.githubusercontent.com/76238470/200022887-b930fb21-306f-439c-b47b-ef0ec554160c.png)
This is how mzj21 does it at https://github.com/mzj21/FallGuysRecord
From what limited testing I've done, it seems _slightly_ more accurate. Thoughts?
