### ISSUE TITLE
nothing is working and i have installed the backup

### ISSUE THREAD

**Issue by Letrobro** [ThreesFG/FallGuysStats#2]

**Comment by ThreesFG** [comment]
Are you testing the code by compiling locally, or using my .zip file? If you're using my .zip file, I realized that I didn't include in the instructions that my .zip file that you still need all of the files from the original Fall Guys Stats program. Please make sure you have all of those, and any further details you could provide would be helpful.

**Comment by Letrobro** [comment]
> Are you testing the code by compiling locally, or using my .zip file? If you're using my .zip file, I realized that I didn't include in the instructions that my .zip file that you still need all of the files from the original Fall Guys Stats program. Please make sure you have all of those, and any further details you could provide would be helpful.

**Comment by Letrobro** [comment]
sorry
yes i used the original stats so idk whats wrong

**Comment by Letrobro** [comment]
DW I FIXED
