### ISSUE TITLE
Can't connect Fall Guys Game Location to the stat tracker

### ISSUE THREAD

**Issue by Bigpp696969** [ThreesFG/FallGuysStats#3]
It doesn't work, when on the browser in the tracker settings to locate my Fall guys game folder, an error message is displayed "The path is not of a legal form." I'm on Epic.
https://github.com/ThreesFG/FallGuysStats/issues/3

**Comment by riceeater12345** [comment]
It doesn't work for me either. I have the same path C:\Program Files\Epic Games\FallGuys\FallGuys_client_game.exe. Did I do something wrong?

**Comment by Micdu70** [comment]
Yup, this issue was already reported here => ShootMe/FallGuysStats#125
